enforce_secure_profile: false
listeners:
- query_port: 25577
  motd: '&1MOTD DE TEST'
  tab_list: SERVER
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: lobby
  ping_passthrough: false
  priorities:
  - lobby
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 100
  tab_size: 60
  force_default_server: true
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  admin:
  - bungeecord.command.server
  - bungeecord.command.list
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - bungeecord.command.kick
log_pings: true
connection_throttle_limit: 3
server_connect_timeout: 5000
timeout: 30000
player_limit: 100
prevent_proxy_connections: false
ip_forward: true
groups:
  __sx:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
stats: 37d60d6d-e5cb-4651-9a61-f434dfb089bb
online_mode: true
forge_support: false
disabled_commands:
- null
servers:
  lobby:
    motd: sx Lobby
    address: localhost:25566
    restricted: false
  mining:
    motd: sx Mining
    address: localhost:25567
    restricted: false
  build:
    motd: sx Build
    address: localhost:25568
    restricted: false
